### ISSUE TITLE
Not opening Android App.

### ISSUE THREAD

**Issue by leossmith** [BranchMetrics/air-ane-branch-deep-linking#24]
I have implemented the ANE on my Android app and trying to test it. Although links work, it looks like the link does not identify that the app is already installed on my Smartphone and just sends me to the link to redownload it.

Testing on Android 6.0.1

**Comment by aaustin** [comment]
Hey @leossmith - Thanks for the note. This is not an issue with the ANE SDK, but more an issue with the configuration of your Branch links. Let's get you sorted.

Please confirm the following:
1. Your app's testbed package name matches the package name on the Branch dashboard
2. You correctly add the URI scheme to your `..app.xml` as shown in this link https://dev.branch.io/getting-started/sdk-integration-guide/guide/adobe/#android-projects-1

It'd be great if you could share a link for me to help if the above two don't fix it.

**Comment by leossmith** [comment]
Hi there,

so i have the following:

`<activity>
					<intent-filter>
						<action android:name="android.intent.action.MAIN"/>
						<category android:name="android.intent.category.LAUNCHER"/>
					</intent-filter>
					<intent-filter >
				        <action android:name="android.intent.action.VIEW" />
				        <category android:name="android.intent.category.DEFAULT" />
				        <category android:name="android.intent.category.BROWSABLE" />
				         <data android:scheme="pokemoncpcalculator" />
				    </intent-filter>
				</activity>`

shouldn't the link to send to a user be pokemoncpcalculator:// ? I currently don't use any links to navigate inside the app, i am just trying to open the app when the user clicks on a "usa this app" button.

**Comment by aaustin** [comment]
Mind sharing your Branch key so that I can review your dashboard settings? I'm worried the package name you've entered doesn't match your app.

`pokenmoncpcalculator://` sounds like it should work just fine so it's likely a package name mismatch.

**Comment by leossmith** [comment]
This is my test key: key_test_ikCdgixIW1yzP6lrDG267aonvvkqZOs9

When i visit the tesitng link: pokemoncpcalculator.test-app.link it takes me to the page to download the app, although the app is already installed.

**Comment by aaustin** [comment]
Hey @leossmith - Sorry for the delay. I just took a look at [your dashboard](https://dashboard.branch.io/settings/link) and for some reason `Always open the app` on both test and live is unchecked. Can you please check these values, then save and try again? I think you'll find it'll start working.

<img width="270" alt="screen shot 2016-09-28 at 10 48 25 am" src="https://cloud.githubusercontent.com/assets/1332632/18906769/3285b39a-8569-11e6-9039-36918c82a670.png">

Not sure how they were unchecked. We set them to true by default for all new apps created.
